name: ChatMessenger
author: Zeryther
version: 1.2.1
website: https://github.com/Zeryther/ChatMessenger
main: me.zeryther.chatmessenger.ChatMessengerPlugin

commands:
  msg:
    description: Private Message a player
    aliases: [w, whisper, tell, message, pm, pn, m]
  reply:
    description: Reply to a private message
    aliases: [r, rep, rply]
  blockmsg:
    description: Disable private messaging
    aliases: [blocktell, blockwhisper, blockpm, bmsg]
  socialspy:
    description: Spy on private messages
    aliases: [spy]
  chatreload:
    description: Reload ChatMessenger
    aliases: [cmreload]